/* Category */
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_SOME_CATEGORIES = "GET_SOME_CATEGORIES";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const ADD_CATEGORY = "ADD_CATEGORY";

/* Product */
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_PRODUCTS_BY_CATEGORIES = "GET_PRODUCTS_BY_CATEGORIES";
export const GET_SOME_PRODUCTS_BY_CATEGORIES =
  "GET_SOME_PRODUCTS_BY_CATEGORIES";
export const GET_PRODUCTS_BY_CATEGORIES_ERROR =
  "GET_PRODUCTS_BY_CATEGORIES_ERROR";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_BY_ID_ERROR = "GET_PRODUCT_BY_ID_ERROR";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
export const DELETE_PRODUCT_BY_ID_ERROR = "DELETE_PRODUCT_BY_ID_ERROR";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";
export const GET_PRODUCT_BY_CODE = "GET_PRODUCT_BY_CODE";
export const GET_PRODUCT_BY_CODE_ERROR = "GET_PRODUCT_BY_CODE_ERROR";

/* User */

/* Loading */
export const SET_LOADING = "SET_LOADING";

// alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// user

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ADMIN_lOADED = "ADMIN_lOADED";
export const ADMIN_lOADING_FAILED = "ADMIN_lOADING_FAILED";
