/* Category */
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_SOME_CATEGORIES = 'GET_SOME_CATEGORIES'
export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID'

/* Product */
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'
export const GET_PRODUCTS_BY_CATEGORIES = 'GET_PRODUCTS_BY_CATEGORIES'
export const GET_SOME_PRODUCTS_BY_CATEGORIES = 'GET_SOME_PRODUCTS_BY_CATEGORIES'
export const GET_PRODUCTS_BY_CATEGORIES_ERROR =
  'GET_PRODUCTS_BY_CATEGORIES_ERROR'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR'

/* User */

/* Loading */
export const SET_LOADING = 'SET_LOADING'
